name: dart_code_metrics
version: 5.7.6
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.1.0 <5.14.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.3
  args: ^2.7.0
  collection: ^1.19.1
  crypto: ^3.0.6
  dart_code_metrics_presets: ^2.21.0
  file: ^7.0.1
  glob: ^2.1.3
  html: ">=0.15.0 <1.0.0"
  http:
  meta: ^1.16.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  source_span: ^1.10.0
  uuid: ^4.5.1
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.3

dev_dependencies:
  coverage: ^1.11.1
  intl: ">=0.17.0 <0.19.0"
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
